// src/Themes/default/LightPortal/components/options/NumberOption.vue
<template>
  <div>
    <input type="number" :id="id" :name="name" :value="value" :min="min" :max="max" :step="step" />
    <span v-if="postfix" class="postfix">{{ postfix }}</span>
  </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  id: {
    type: String,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  value: {
    type: String,
    default: '',
  },
  option: {
    type: Object,
    required: true,
  },
});

const min = computed(() => props.option.min ?? 0);
const max = computed(() => props.option.max);
const step = computed(() => props.option.step ?? (props.option[0] === 'int' ? 1 : 0.01));
const postfix = computed(() => props.option.postfix);
</script>

// resources/components/plugins/options/NumberOption.svelte
<script>
  import Postfix from './Postfix.svelte';

  let { id, name, value = '', option = { postfix: false } } = $props();

  let min = $derived(option.min ?? 0);
  let max = $derived(option.max);
  let step = $derived(option.step ?? (option[0] === 'int' ? 1 : 0.01));
  let postfix = $derived(option.postfix);
</script>

<div>
  <input type="number" bind:value id={id} name={name} min={min} max={max} step={step} />

  {#if postfix}
    <Postfix>{postfix}</Postfix>
  {/if}
</div>
