// src/Themes/default/LightPortal/components/options/RangeOption.vue
<template>
  <div>
    <input type="range" :id="id" :name="name" :value="value" :min="min" :max="max" :step="step" />
    <span class="range_field" v-text="value"></span>
  </div>
</template>

<script>
export default {
  name: 'RangeOption',
};
</script>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  id: {
    type: String,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  value: {
    type: String,
    default: '',
  },
  option: {
    type: Object,
    required: true,
  },
});

const min = computed(() => props.option.min ?? 0);
const max = computed(() => props.option.max ?? 100);
const step = computed(() => props.option.step ?? 1);
</script>

// resources/components/plugins/options/RangeOption.svelte
<script>
  let { id, name, value = 0, option = {} } = $props();

  const min = $derived(option.min ?? 0);
  const max = $derived(option.max ?? 100);
  const step = $derived(option.step ?? 1);
</script>

<div>
  <input type="range" bind:value {id} {name} {min} {max} {step} />
  <span class="range_field">{value}</span>
</div>

<style>
  .range_field {
    margin-left: 6px;
    font-weight: bold;
  }
</style>
