// src/Themes/default/LightPortal/components/options/SelectOption.vue
<template>
  <Multiselect
    mode="single"
    :id="id"
    :name="name"
    :options="options"
    :value="value"
    :append-to-body="true"
    :can-clear="false"
    :native-support="true"
    :placeholder="$t('lp_plugins_select')"
    :no-results-text="$t('no_matches')"
  />
</template>

<script setup>
import { computed } from 'vue';
import Multiselect from '@vueform/multiselect';

const props = defineProps({
  id: {
    type: String,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  value: {
    type: String,
    default: '',
  },
  option: {
    type: Object,
    required: true,
  },
});

const extra = computed(() => props.option[2]);

const options = computed(() =>
  extra.value ? Object.entries(extra.value).map(([value, label]) => ({ label, value })) : null
);
</script>

// resources/components/plugins/options/SelectOption.svelte
<script>
  import { _ } from 'svelte-i18n';
  import Svelecte, { config } from 'svelecte';

  config.i18n.empty = $_('no_options');
  config.i18n.nomatch = $_('no_matches');

  let {
    id,
    name,
    value = '',
    option = {},
    multiple = false,
    clearable = false
  } = $props();

  const params = $derived(option[2]);
  const options = $derived(
    params ? Object.entries(params).map(([value, label]) => ({ value, label })) : []
  );
</script>

<Svelecte
  {options}
  inputId={id}
  {name}
  bind:value
  {multiple}
  {clearable}
  placeholder={$_('lp_plugins_select')}
/>
