// src/Themes/default/LightPortal/components/EditForm.vue
<template>
  <div class="edit_form" @keyup.esc="handleCancel">
    <MarkdownEditor v-model="message" required />

    <div class="comment_edit_buttons">
      <Button v-show="message" @click="handleSubmit" tag="span" icon="save">
        {{ $t('save') }}
      </Button>
      <Button @click="handleCancel" tag="span" icon="undo">
        {{ $t('modify_cancel') }}
      </Button>
    </div>
  </div>
</template>

<script setup>
import { defineEmits, ref } from 'vue';
import MarkdownEditor from './MarkdownEditor.vue';
import Button from './BaseButton.vue';

const props = defineProps({
  comment: {
    type: {
      id: Number,
      message: String,
    },
    required: true,
  },
});

const emit = defineEmits(['submit', 'cancel']);

const message = ref(props.comment.message);

const handleSubmit = () => emit('submit', { id: props.comment.id, content: message.value });
const handleCancel = () => emit('cancel');
</script>

// resources/components/comments/EditForm.svelte
<script>
  import { _ } from 'svelte-i18n';
  import { MarkdownEditor } from './index.js';
  import Button from '../BaseButton.svelte';

  let { comment, submit, cancel } = $props();
  let message = $state(comment.message);

  const handleSubmit = () => {
    submit({ id: comment.id, content: message });
  };

  const handleCancel = () => {
    cancel();
  };
</script>

<div class="edit_form">
  <MarkdownEditor bind:message required />

  <div class="comment_edit_buttons">
    {#if message.length}
      <Button onclick={handleSubmit} tag="span" icon="save">
        {$_('save')}
      </Button>
    {/if}
    <Button onclick={handleCancel} tag="span" icon="undo">
      {$_('modify_cancel')}
    </Button>
  </div>
</div>
