// src/Themes/default/LightPortal/components/ReplyForm.vue
<template>
  <div v-if="userStore.id" class="reply_form roundframe descbox">
    <MarkdownEditor v-model="message" :placeholder="$t('add_comment')" />

    <slot></slot>

    <Button icon="submit" name="comment" :disabled="!message" @click="submit">
      {{ $t('post') }}
    </Button>
  </div>
</template>

<script setup>
import { defineEmits, ref } from 'vue';
import { useUserStore } from '@scripts/comment_stores.js';
import MarkdownEditor from './MarkdownEditor.vue';
import Button from './BaseButton.vue';

const props = defineProps({
  parent: {
    type: Object,
    default: null,
  },
});

const emit = defineEmits(['submit']);

const userStore = useUserStore();

const message = ref('');

const submit = () => {
  emit('submit', { parent: props.parent, content: message.value });

  message.value = '';
};
</script>

// resources/components/comments/ReplyForm.svelte
<script>
  import { _ } from 'svelte-i18n';
  import { useUserStore } from '../../js/stores.js';
  import { MarkdownEditor } from './index.js';
  import Button from '../BaseButton.svelte';

  let { parent, submit, children } = $props();
  let message = $state('');

  const onclick = () => {
    submit({ parent, content: message });
    message = '';
  };
</script>

{#if $useUserStore.id}
  <div class="reply_form roundframe descbox">
    <MarkdownEditor bind:message placeholder={$_('add_comment')} />

    {@render children?.()}

    <Button icon="submit" name="comment" disabled={message.length === 0} {onclick}>
      {$_('post')}
    </Button>
  </div>
{/if}
