// resources/components/plugins/options/TextOption.svelte
<script>
  let { id, name, value = '', option = {} } = $props();

  let pattern = $derived(option.pattern);
  let placeholder = $derived(option.placeholder);
  let required = $derived(option.required);
</script>

<div>
  <input type="text" {id} {name} bind:value {pattern} {placeholder} {required} />
</div>

// src/Themes/default/LightPortal/components/options/TextOption.vue
<template>
  <div>
    <input
      type="text"
      :id="id"
      :name="name"
      :value="value"
      :pattern="pattern"
      :placeholder="placeholder"
      :required="required"
    />
  </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  id: {
    type: String,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  value: {
    type: String,
    default: '',
  },
  option: {
    type: Object,
    required: true,
  },
});

const pattern = computed(() => props.option.pattern);
const placeholder = computed(() => props.option.placeholder);
const required = computed(() => props.option.required);
</script>
