// resources/components/BaseButton.svelte
<script>
  import { useIconStore } from '../js/stores.js';

  let { tag = 'button', icon = '', children, ...rest } = $props();

  const button = $derived(
    tag === 'button'
      ? {
          tag: 'button',
          class: 'button',
          role: undefined
        }
      : {
          tag: 'span',
          class: undefined,
          role: 'button'
        }
  );

  const preparedIcon = $derived($useIconStore[icon] ?? '');
</script>

<svelte:element this={button.tag} {...rest} class={[button.class, rest.class]} role={button.role}>
  {@html preparedIcon}
  {@render children?.()}
</svelte:element>

// src/Themes/default/LightPortal/components/BaseButton.vue
<template>
  <component :is="button.tag" :class="button.class" :role="button.role">
    <span v-html="preparedIcon"></span>
    <slot></slot>
  </component>
</template>

<script setup>
import { computed } from 'vue';
import { useIconStore } from '@scripts/base_stores.js';

const iconStore = useIconStore();

const props = defineProps({
  tag: {
    type: String,
    default: 'button',
  },
  icon: {
    type: String,
    default: '',
  },
});

const button = computed(() =>
  props.tag === 'button'
    ? {
        tag: 'button',
        class: 'button',
        role: undefined,
      }
    : {
        tag: 'span',
        class: undefined,
        role: 'button',
      }
);

const preparedIcon = computed(() => iconStore[props.icon] ?? '');
</script>
