// resources/components/comments/CommentItem.svelte
<script>
  import { _ } from 'svelte-i18n';
  import { fade } from 'svelte/transition';
  import { useUserStore } from '../../js/stores.js';
  import { CommentItem, EditForm, ReplyForm, MarkdownPreview } from './index.js';
  import Button from '../BaseButton.svelte';

  /**
   * @type {{
   *   comment: {
   *     can_edit: boolean,
   *     authorial: boolean,
   *     poster: {
   *       name: string,
   *       avatar: string
   *     },
   *     extra_buttons: array,
   *     human_date: string,
   *     published_at: number
   *   }
   * }}
   */
  let { comment, index, level = 1, addComment, updateComment, removeComment } = $props();
  let isHover = $state(false);
  let replyMode = $state(false);
  let editMode = $state(false);
  let parent = $state();

  const { id: userId, is_admin: isAdmin } = $useUserStore;
  const showReplyButton = $derived(level < 5 && userId !== comment.poster.id);
  const showRemoveButton = $derived(comment.poster.id === userId || isAdmin);
  const canEdit = $derived(
    comment.can_edit &&
      (!comment.replies || !comment.replies.length) &&
      comment.poster.id === userId
  );

  const submit = (newComment) => {
    addComment(newComment);
    replyMode = false;
  };

  const update = (updatedComment) => {
    updateComment(updatedComment);
    comment.message = updatedComment.content;
    editMode = false;
  };

  const itemType = 'https://schema.org/Comment';
</script>

<li
  transition:fade
  bind:this={parent}
  id={`comment${comment.id}`}
  class={`col-xs-12 generic_list_wrapper bg ${index % 2 === 0 ? 'even' : 'odd'}`}
  data-id={comment.id}
  data-author={comment.poster.id}
  itemprop="comment"
  itemscope
  itemtype={itemType}
>
  <div class="comment_wrapper" id={`comment=${comment.id}`}>
    <div class="comment_avatar">
      <span>{@html comment.poster.avatar}</span>
      {#if comment.authorial}
        <span class="new_posts">{$_('author')}</span>
      {/if}
    </div>
    <div class="comment_entry bg {index % 2 === 0 ? 'odd' : 'even'}">
      <div class="comment_title">
        <span class="bg {index % 2 === 0 ? 'even' : 'odd'}" data-id={comment.id} itemprop="creator"
          >{comment.poster.name}</span
        >
        <div class="comment_date bg {index % 2 === 0 ? 'even' : 'odd'}">
          <span itemprop="datePublished" content={comment.published_at}>
            {@html comment.human_date}
            <a class="bbc_link" href={`#comment=${comment.id}`}>#{comment.id}</a>
          </span>
        </div>
      </div>

      {#if editMode}
        <EditForm {comment} submit={update} cancel={() => (editMode = false)} />
      {:else}
        <MarkdownPreview
          content={comment.message}
          class="comment_content"
          style="border: none;"
          itemprop="text"
        />
        {#if userId}
          <div class="comment_buttons">
            {#if showReplyButton}
              <Button onclick={() => (replyMode = !replyMode)} tag="span" icon="reply">
                {$_('reply')}
              </Button>
            {/if}

            {#if canEdit}
              <Button onclick={() => (editMode = true)} tag="span" icon="edit">
                {$_('modify')}
              </Button>
            {/if}

            {#each comment.extra_buttons as button}
              {@html button}
            {/each}

            {#if showRemoveButton}
              <Button
                class={isHover ? 'error' : undefined}
                onmouseover={() => (isHover = true)}
                onmouseleave={() => (isHover = false)}
                onclick={() => removeComment(parent.dataset.id)}
                tag="span"
                icon="remove"
              >
                {$_('remove')}
              </Button>
            {/if}
          </div>
        {/if}
      {/if}
    </div>

    {#if replyMode}
      <ReplyForm parent={parent.dataset} {submit}>
        <Button class="active" onclick={() => (replyMode = false)}>
          {$_('modify_cancel')}
        </Button>
      </ReplyForm>
    {/if}

    {#if comment.replies.length}
      <ul class="comment_list row">
        {#each comment.replies as reply}
          <CommentItem
            comment={reply}
            index={index + 1}
            level={level + 1}
            addComment={submit}
            updateComment={update}
            {removeComment}
          />
        {/each}
      </ul>
    {/if}
  </div>
</li>

// src/Themes/default/LightPortal/components/CommentItem.vue
<template>
  <li
    ref="parent"
    :id="`comment${comment.id}`"
    :class="['col-xs-12', 'generic_list_wrapper', 'bg', ['even', 'odd'][index % 2]]"
    :data-id="comment.id"
    :data-author="comment.poster.id"
    itemprop="comment"
    itemscope
    itemtype="https://schema.org/Comment"
  >
    <div class="comment_wrapper" :id="`comment=${comment.id}`">
      <div class="comment_avatar">
        <span v-html="comment.poster.avatar"></span>
        <span v-if="comment.authorial" class="new_posts">{{ $t('author') }}</span>
      </div>
      <div class="comment_entry bg" :class="['odd', 'even'][index % 2]">
        <div class="comment_title">
          <span
            class="bg"
            :class="['even', 'odd'][index % 2]"
            :data-id="comment.id"
            itemprop="creator"
            v-text="comment.poster.name"
          ></span>
          <div class="comment_date bg" :class="['even', 'odd'][index % 2]">
            <span itemprop="datePublished" :content="comment.published_at">
              <span v-html="comment.human_date"></span>
              <a class="bbc_link" :href="`#comment=${comment.id}`" v-text="`#${comment.id}`"></a>
            </span>
          </div>
        </div>

        <template v-if="editMode">
          <EditForm :comment="comment" @submit="update" @cancel="editMode = false"></EditForm>
        </template>
        <template v-else>
          <MarkdownPreview
            :content="comment.message"
            class="comment_content"
            :style="{ border: 'none' }"
            itemprop="text"
          />
          <div v-if="userId" class="comment_buttons">
            <Button v-if="showReplyButton" @click="replyMode = !replyMode" tag="span" icon="reply">
              {{ $t('reply') }}
            </Button>
            <Button v-if="canEdit" @click="editMode = true" tag="span" icon="edit">
              {{ $t('modify') }}
            </Button>
            <template v-for="button in comment.extra_buttons">
              <span v-html="button"></span>
            </template>
            <Button
              v-if="showRemoveButton"
              :class="isHover ? 'error' : undefined"
              @mouseover="isHover = true"
              @mouseleave="isHover = false"
              @click.prevent="remove($el.dataset.id)"
              tag="span"
              icon="remove"
            >
              {{ $t('remove') }}
            </Button>
          </div>
        </template>
      </div>

      <keep-alive>
        <ReplyForm v-if="replyMode" :parent="$el.dataset" @submit="add">
          <Button class="active" @click.self="replyMode = false">{{ $t('modify_cancel') }}</Button>
        </ReplyForm>
      </keep-alive>

      <ListTransition v-if="comment.replies" class="comment_list row">
        <CommentItem
          v-for="reply in comment.replies"
          :key="reply.id"
          :comment="reply"
          :index="index + 1"
          :level="level + 1"
          @add-comment="add"
          @update-comment="update"
          @remove-comment="remove"
        />
      </ListTransition>
    </div>
  </li>
</template>

<script setup>
import { defineOptions, defineEmits, ref, computed } from 'vue';
import { useUserStore } from '@scripts/comment_stores.js';
import ListTransition from './ListTransition.vue';
import EditForm from './EditForm.vue';
import ReplyForm from './ReplyForm.vue';
import MarkdownPreview from './MarkdownPreview.vue';
import Button from './BaseButton.vue';

defineOptions({
  name: 'CommentItem',
});

const { id: userId, is_admin: isAdmin } = useUserStore();

const props = defineProps({
  comment: {
    type: {
      id: Number,
      published_at: Number,
      human_date: String,
      can_edit: Boolean,
      authorial: Boolean,
      poster: {
        id: Number,
        name: String,
        avatar: String,
      },
      extra_buttons: Array,
      replies: Array,
    },
    required: true,
  },
  index: {
    type: Number,
    required: true,
  },
  level: {
    type: Number,
    required: false,
    default: 1,
  },
});

const emit = defineEmits(['add-comment', 'update-comment', 'remove-comment']);

const isHover = ref(false);
const replyMode = ref(false);
const editMode = ref(false);
const parent = ref();

const showReplyButton = computed(() => props.level < 5 && userId !== props.comment.poster.id);

const showRemoveButton = computed(() => props.comment.poster.id === userId || isAdmin);

const canEdit = computed(
  () =>
    props.comment.can_edit &&
    (!props.comment.replies || !props.comment.replies.length) &&
    props.comment.poster.id === userId
);

const add = (comment) => {
  emit('add-comment', comment);
  replyMode.value = false;
};

const update = (comment) => {
  emit('update-comment', comment);
  props.comment.message = comment.content;
  editMode.value = false;
};

const remove = (id) => {
  emit('remove-comment', id);
};
</script>
