// resources/components/plugins/PluginOptionItem.svelte
<script>
  import { _ } from 'svelte-i18n';
  import { useContextStore } from '../../js/stores.js';
  import {
    CallbackOption,
    CheckOption,
    ColorOption,
    DescOption,
    LargeTextOption,
    MultiSelectOption,
    NumberOption,
    Postfix,
    RangeOption,
    SelectOption,
    TextOption,
    TitleOption,
    UrlOption
  } from './options/index.js';

  let { option, plugin } = $props();

  const contextStore = $useContextStore;
  const type = $derived(option[0]);
  const name = $derived(option[1]);
  const id = $derived(`${plugin}.${name}`);
  const value = $derived(contextStore[`lp_${plugin}`]?.[name]);
  const { postfix, subtext } = $derived(option);
  const showLabel = $derived(!['callback', 'title', 'desc', 'check'].includes(type));
  const optionType = $derived(['float', 'int'].includes(type) ? 'number' : type);

  const dynamicProps = $derived.by(() => {
    switch (optionType) {
      case 'callback':
        return { Component: CallbackOption, option };
      case 'check':
        return { Component: CheckOption, id, name, value };
      case 'color':
        return { Component: ColorOption, id, name, value };
      case 'desc':
        return { Component: DescOption, id };
      case 'large_text':
        return { Component: LargeTextOption, id, name, value };
      case 'multiselect':
        return { Component: MultiSelectOption, id, name, value, option };
      case 'number':
        return { Component: NumberOption, id, name, value, option };
      case 'range':
        return { Component: RangeOption, id, name, value, option };
      case 'select':
        return { Component: SelectOption, id, name, value, option };
      case 'text':
        return { Component: TextOption, id, name, value, option };
      case 'title':
        return { Component: TitleOption, id };
      case 'url':
        return { Component: UrlOption, id, name, value, option };
      default:
        return null;
    }
  });

  const Component = $derived(dynamicProps?.Component);
</script>

<div>
  {#if showLabel}
    <label for={id}>
      {$_(`lp_${id}`)}
      {#if postfix && optionType !== 'number'}
        <Postfix>({postfix})</Postfix>
      {/if}
    </label>
  {/if}

  {#if dynamicProps}
    <Component {...dynamicProps} />
  {/if}

  {#if subtext}
    <div class="roundframe">{@html subtext}</div>
  {/if}
</div>

// src/Themes/default/LightPortal/components/PluginOptionItem.vue
<template>
  <div>
    <label v-if="showLabel" :for="id">
      {{ $t(`lp_${id}`) }}
      <span v-if="postfix && isType !== 'number'" class="postfix">({{ postfix }})</span>
    </label>
    <keep-alive>
      <component :is="dynamicComponentProps.is" v-bind="dynamicComponentProps"></component>
    </keep-alive>
    <div v-if="subtext" class="roundframe" v-html="subtext"></div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useContextStore } from '../../scripts/light_portal/dev/base_stores.js';
import CallbackOption from './options/CallbackOption.vue';
import CheckOption from './options/CheckOption.vue';
import ColorOption from './options/ColorOption.vue';
import DescOption from './options/DescOption.vue';
import LargeTextOption from './options/LargeTextOption.vue';
import MultiSelectOption from './options/MultiSelectOption.vue';
import NumberOption from './options/NumberOption.vue';
import RangeOption from './options/RangeOption.vue';
import SelectOption from './options/SelectOption.vue';
import TextOption from './options/TextOption.vue';
import TitleOption from './options/TitleOption.vue';
import UrlOption from './options/UrlOption.vue';

const contextStore = useContextStore();

const props = defineProps({
  option: {
    type: Object,
    required: true,
  },
  plugin: {
    type: String,
    required: true,
  },
});

const type = computed(() => props.option[0]);
const name = computed(() => props.option[1]);
const id = computed(() => `${props.plugin}.${name.value}`);
const value = computed(() => contextStore[`lp_${props.plugin}`]?.[name.value]);

const showLabel = computed(() => !['callback', 'title', 'desc', 'check'].includes(type.value));
const postfix = computed(() => props.option.postfix);
const subtext = computed(() => props.option.subtext);

const isType = computed(() => (['float', 'int'].includes(type.value) ? 'number' : type.value));

const dynamicComponentProps = computed(() => {
  const typeMap = {
    callback: { is: CallbackOption, option: props.option },
    check: {
      is: CheckOption,
      id: id.value,
      name: name.value,
      value: value.value,
    },
    color: {
      is: ColorOption,
      id: id.value,
      name: name.value,
      value: value.value,
    },
    desc: { is: DescOption, id: id.value },
    large_text: {
      is: LargeTextOption,
      id: id.value,
      name: name.value,
      value: value.value,
    },
    multiselect: {
      is: MultiSelectOption,
      id: id.value,
      name: name.value,
      value: value.value,
      option: props.option,
    },
    number: {
      is: NumberOption,
      id: id.value,
      name: name.value,
      value: value.value,
      option: props.option,
    },
    range: {
      is: RangeOption,
      id: id.value,
      name: name.value,
      value: value.value,
      option: props.option,
    },
    select: {
      is: SelectOption,
      id: id.value,
      name: name.value,
      value: value.value,
      option: props.option,
    },
    text: {
      is: TextOption,
      id: id.value,
      name: name.value,
      value: value.value,
      option: props.option,
    },
    title: { is: TitleOption, id: id.value },
    url: {
      is: UrlOption,
      id: id.value,
      name: name.value,
      value: value.value,
      option: props.option,
    },
  };

  return typeMap[isType.value] || false;
});
</script>
