// src/Themes/default/LightPortal/components/PluginOptionList.vue
<template>
  <br class="clear" />
  <transition name="fade">
    <div v-show="show" class="roundframe" :id="blockId">
      <div class="title_bar">
        <h5 class="titlebg">{{ $t('settings') }}</h5>
      </div>
      <div class="noticebox">
        <form ref="form" class="form_settings" :id="formId" @submit.prevent="saveSettings">
          <input type="hidden" name="plugin_name" :value="item.snake_name" />
          <input type="hidden" :name="sessionVar" :value="sessionId" />

          <PluginOptionItem
            v-for="(option, index) in item.settings"
            :option="option"
            :plugin="String(item.snake_name)"
            :key="index"
          />
        </form>
      </div>
      <div class="footer">
        <span class="infobox floatleft" :class="success ? 'show' : undefined">
          {{ $t('settings_saved') }}
        </span>
        <Button icon="close" @click="emit('hide')">{{ $t('find_close') }}</Button>
        <Button v-if="item.saveable" icon="save" :form="formId" type="submit">
          {{ $t('save') }}
        </Button>
      </div>
    </div>
  </transition>
</template>

<script setup>
import { defineEmits, ref, computed } from 'vue';
import { useContextStore } from '@scripts/base_stores.js';
import { useAppStore } from '@scripts/plugin_stores.js';
import Button from './BaseButton.vue';
import PluginOptionItem from './PluginOptionItem.vue';

const { sessionVar, sessionId } = useAppStore();
const { postUrl } = useContextStore();

const props = defineProps({
  item: {
    type: {
      snake_name: String,
      settings: Array,
      saveable: Boolean,
    },
    required: true,
  },
  show: {
    type: Boolean,
    default: false,
  },
});

const emit = defineEmits(['hide']);

const success = ref(false);
const form = ref();

const blockId = computed(() => props.item.snake_name + '_' + sessionId + '_settings');
const formId = computed(() => props.item.snake_name + '_form_' + sessionId);

const saveSettings = async () => {
  let formData = new FormData(form.value),
    lpCheckboxes = form.value.querySelectorAll('input[type=checkbox]');

  lpCheckboxes.forEach(function (val) {
    formData.append(val.getAttribute('name'), val.matches(':checked'));
  });

  const { data } = await axios.post(postUrl, formData, {
    headers: {
      'Content-Type': 'multipart/form-data',
    },
  });

  if (data.success) {
    success.value = true;

    setInterval(() => (success.value = false), 3000);
  }
};
</script>

// resources/components/plugins/PluginOptionList.svelte
<script>
  import { _ } from 'svelte-i18n';
  import { get } from 'svelte/store';
  import { fade } from 'svelte/transition';
  import { useContextStore, useAppStore } from '../../js/stores.js';
  import { PluginOptionItem } from './index.js';
  import Button from '../BaseButton.svelte';

  /** @type {{ item: { snake_name: string, saveable: boolean, settings: array } }} */
  let { item, hide } = $props();
  let success = $state(false);
  let form = $state();

  const { sessionId, sessionVar } = get(useAppStore);
  const { postUrl } = get(useContextStore);

  const blockId = $derived(`${item.snake_name}_${sessionId}_settings`);
  const formId = $derived(`${item.snake_name}_form_${sessionId}`);

  const saveSettings = async (e) => {
    e.preventDefault();

    const formData = new FormData(form);
    const lpCheckboxes = form.querySelectorAll('input[type=checkbox]');

    lpCheckboxes.forEach((val) => {
      formData.append(val.getAttribute('name'), val.checked);
    });

    const { data } = await axios.post(String(postUrl), formData, {
      headers: {
        'Content-Type': 'multipart/form-data'
      }
    });

    if (data.success) {
      success = true;
      setTimeout(() => success = false, 3000);
    }
  };
</script>

<div class="roundframe" id={blockId} transition:fade>
  <div class="title_bar">
    <h5 class="titlebg">{$_('settings')}</h5>
  </div>

  <div class="noticebox">
    <form bind:this={form} class="form_settings" id={formId} onsubmit={(e) => saveSettings(e)}>
      <input type="hidden" name="plugin_name" value={item.snake_name} />
      <input type="hidden" name={sessionVar} value={sessionId} />

      {#each item.settings as option}
        <PluginOptionItem {option} plugin={item.snake_name} />
      {/each}
    </form>
  </div>

  <div class="footer">
    <span class="infobox floatleft {success ? 'show' : ''}">
      {$_('settings_saved')}
    </span>

    <Button icon="close" onclick={hide}>{$_('find_close')}</Button>

    {#if item.saveable}
      <Button icon="save" form={formId} type="submit">
        {$_('save')}
      </Button>
    {/if}
  </div>
</div>
